import Head from "next/head";
import { useEffect, useState } from "react";
import Intro from "../components/Intro";
import { isConnected } from "../utils/connects";

export default function Home() {
  return (
    <div className="w-full h-full flex items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
    </div>
  );
}
